---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/29/2024 6:57 PM
---

local String = {}

function String.split(s, sep, pattern)
    sep = sep or '.'
    sep = sep ~= '' and sep or '.'
    sep = not pattern and sep:gsub('([^%w])', '%%%1') or sep

    local fields = {}
    local start_idx, end_idx = s:find(sep)
    local last_find = 1
    while start_idx do
        local substr = s:sub(last_find, start_idx - 1)
        if substr:len() > 0 then table.insert(fields, s:sub(last_find, start_idx - 1)) end
        last_find = end_idx + 1
        start_idx, end_idx = s:find(sep, end_idx + 1)
    end
    local substr = s:sub(last_find)
    if substr:len() > 0 then table.insert(fields, s:sub(last_find)) end
    return fields
end

function String.trim(s)
    return (s:gsub([[^%s*(.-)%s*$]], '%1'))
end


function String.starts_with(s, start)
    return s:find(start, 1, true) == 1
end

return String