---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 6/23/2026 12:46 PM
---

require("util")
local AIHelper = {}

function AIHelper.get_enemy_unit_settings(group_size)
    return {
        destroy_when_commands_fail = true,
        allow_try_return_to_spawner = true,
        size_in_group = group_size or 1
    }
end

function AIHelper.get_controllable_unit_setting(group_size)
    return {
        destroy_when_commands_fail = false,
        allow_try_return_to_spawner = false,
        size_in_group = group_size or 1
    }
end

---
--- Unit's steering setting.  When an unit doesn't set steering, the default is stay = 1.2, move = 3
---
function AIHelper.get_steering_setting(move_radius, stay_radius)
    return {
        move = {
            radius = move_radius
        },
        stay = {
            radius = stay_radius
        }
    }
end

function AIHelper.get_player_steering_setting(move_radius, stay_radius)
    return {
        move = {
            ---used in previous unit control for performance enhancement.
            force_unit_fuzzy_goto_behavior = true,
            radius = move_radius
        },
        stay = {
            force_unit_fuzzy_goto_behavior = false,
            radius = stay_radius
        }
    }
end

return AIHelper