---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 3/2/2025 3:48 PM
---

local ArmyEconomyHelper = {}

function ArmyEconomyHelper.create_item (options)
    data:extend({{
        type = "item",
        name = options["prefix"] .. "--controllable--" .. options["name"],
        icons = {
            {
                icon = options["icon"],
                icon_size = 64,
            },
        },
        subgroup = options["subgroup"],
        order = options["prefix"] .. "--controllable--" .. options["name"],
        place_result = options["prefix"] .. "--controllable--" .. options["name"],
        stack_size = options["stack_size"],
        weight = options["weight"] * kg,
    }})
end

function ArmyEconomyHelper.create_recipe (options)
    data:extend({{
        type = "recipe",
        name = options["prefix"] .. "--controllable--" .. options["name"],
        enabled = false,
        energy_required = options["energy_required"],
        ingredients = options["ingredients"],
        category = options["category"],
        allow_as_intermediate = false,
        always_show_made_in = true,
        order = 'z--'..options["prefix"] .. "--controllable--" .. options["name"],
        results = {
            {type="item", name=options["prefix"] .. "--controllable--" .. options["name"], amount=options["amount"]},
        },
        allow_quality = false,
        auto_recycle = false,
    }})
end

function ArmyEconomyHelper.create_deploy_recipe(options)
    data:extend({{
                     type = "recipe",
                     name = 'zdeploy-'..options["prefix"] .. "--controllable--" .. options["name"],
                     enabled = true,
                     icons = {
                         {
                             icon = options["icon"],
                             icon_size = 64,
                         },
                         {
                             icon = "__base__/graphics/icons/signal/signal_D.png",
                             icon_size = 64,
                             scale = 0.25,
                             shift = { 9, 9 }
                         },
                     },
                     energy_required = 3,
                     ingredients = {
                         {type="item", name=options["prefix"] .. "--controllable--" .. options["name"], amount=1},
                     },
                     category = options["category"],
                     allow_as_intermediate = false,
                     always_show_made_in = false,
                     order = 'zdeploy-'..options["prefix"] .. "--controllable--" .. options["name"],
                     results = {
                         {type="item", name=options["prefix"] .. "--controllable--" .. options["name"], amount=1},
                     },
                     hide_from_player_crafting = true,
                     hidden_in_factoriopedia = true,
                     allow_quality = false,
                     auto_recycle = false,
                 }})
end

return ArmyEconomyHelper