---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/6/2024 2:53 PM
---

local AsteroidTriggers = {}

AsteroidTriggers.add_unit_to_asteroid = function(asteroid, race, unit_name, tier, probability)
    local new_trigger = {
        type = "create-entity",
        entity_name = race .. '--' .. unit_name .. '--' .. tier,
        probability = probability,
        trigger_created_entity = true,
        offset_deviation = {
            {
                -0.5,
                -0.5
            },
            {
                0.5,
                0.5
            }
        },
        offsets = {
            {
                0,
                -0.25
            },
        }
    }
    table.insert(asteroid.dying_trigger_effect, new_trigger)
end

return AsteroidTriggers