---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 3/3/2025 1:43 AM
---

local FusionEconomyHelper = {}

local function create_entity()
    local fusion_plant = util.table.deepcopy(data.raw['fusion-generator']['fusion-generator'])
    fusion_plant.type = 'assembling-machine'
    fusion_plant.name = 'fusion-assembling-machine'
    fusion_plant.minable = { mining_time = 0.2, result = "fusion-assembling-machine" }
    fusion_plant.module_slots = 3
    fusion_plant.allowed_effects = { "consumption", "speed", "productivity", "pollution", "quality" }
    fusion_plant.energy_source = {
        type = "electric",
        usage_priority = "secondary-input",
        emissions_per_minute = { pollution = 2 }
    }
    fusion_plant.energy_usage = "2MW"
    fusion_plant.crafting_categories = { "fusion-assembly" }
    fusion_plant.fast_replaceable_group = nil
    fusion_plant.max_fluid_usage = nil
    fusion_plant.crafting_speed = 1
    fusion_plant.graphics_set = {
        animation = {
            north = {
                layers = {
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north.png",
                        frame_count = 6,
                        height = 376,
                        line_length = 3,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -0.0625,
                            -0.0625
                        },
                        width = 244
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north-shadow.png",
                        frame_count = 1,
                        height = 316,
                        line_length = 1,
                        priority = "high",
                        repeat_count = 6,
                        scale = 0.5,
                        shift = {
                            0.390625,
                            0.125
                        },
                        width = 248
                    },
                    --- input 1
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north-input-1.png",
                        height = 78,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -1.015625,
                            2.09375
                        },
                        width = 92,
                        repeat_count = 6,
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north-input-1-shadow.png",
                        height = 58,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -0.765625,
                            2.265625
                        },
                        width = 74,
                        repeat_count = 6,
                    },
                    --- input 2
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north-input-2.png",
                        height = 90,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            0.984375,
                            2.078125
                        },
                        width = 86,
                        repeat_count = 6,
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north-input-2-shadow.png",
                        height = 60,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            1.21875,
                            2.21875
                        },
                        width = 76,
                        repeat_count = 6,
                    }
                }
            },
            east = {
                layers = {
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east.png",
                        frame_count = 6,
                        height = 230,
                        line_length = 3,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            0,
                            -0.03125
                        },
                        width = 370
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east-shadow.png",
                        frame_count = 1,
                        height = 210,
                        line_length = 1,
                        priority = "high",
                        repeat_count = 6,
                        scale = 0.5,
                        shift = {
                            0.265625,
                            0.0625
                        },
                        width = 352
                    },
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east-input-1.png",
                        height = 72,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -2.265625,
                            -0.96875
                        },
                        width = 48,
                        repeat_count = 6,
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east-input-1-shadow.png",
                        height = 42,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -2.0625,
                            -0.90625
                        },
                        width = 60,
                        repeat_count = 6,
                    },
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east-input-2.png",
                        height = 88,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -2.1875,
                            0.90625
                        },
                        width = 70,
                        repeat_count = 6
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east-input-2-shadow.png",
                        height = 46,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -2.171875,
                            1.0625
                        },
                        width = 48,
                        repeat_count = 6
                    }
                }
            },
            south = {
                layers = {
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south.png",
                        frame_count = 6,
                        height = 360,
                        line_length = 3,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            0,
                            0.1875
                        },
                        width = 252
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south-shadow.png",
                        frame_count = 1,
                        height = 304,
                        line_length = 1,
                        priority = "high",
                        repeat_count = 6,
                        scale = 0.5,
                        shift = {
                            0.328125,
                            0.328125
                        },
                        width = 242
                    },
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south-input-1.png",
                        height = 74,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            0.96875,
                            -2.265625
                        },
                        width = 80,
                        repeat_count = 6,
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south-input-1-shadow.png",
                        height = 38,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            1.234375,
                            -2.109375
                        },
                        width = 78,
                        repeat_count = 6,
                    },
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south-input-2.png",
                        height = 88,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -1,
                            -2.3125
                        },
                        width = 88,
                        repeat_count = 6,
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south-input-2-shadow.png",
                        height = 38,
                        line_length = 1,
                        repeat_count = 6,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -0.765625,
                            -2.109375
                        },
                        width = 78,
                        repeat_count = 6,
                    }
                }
            },
            west = {
                layers = {
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west.png",
                        frame_count = 6,
                        height = 240,
                        line_length = 3,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            -0.015625,
                            -0.125
                        },
                        width = 370
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west-shadow.png",
                        frame_count = 1,
                        height = 210,
                        line_length = 1,
                        priority = "high",
                        repeat_count = 6,
                        scale = 0.5,
                        shift = {
                            0.25,
                            0.046875
                        },
                        width = 352
                    },
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west-input-1.png",
                        height = 84,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            2.140625,
                            0.859375
                        },
                        width = 64,
                        repeat_count = 6,
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west-input-1-shadow.png",
                        height = 46,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            2.390625,
                            1.03125
                        },
                        width = 74,
                        repeat_count = 6,
                    },
                    {
                        filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west-input-2.png",
                        height = 68,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            2.25,
                            -1.03125
                        },
                        width = 44,
                        repeat_count = 6,
                    },
                    {
                        draw_as_shadow = true,
                        filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west-input-2-shadow.png",
                        height = 42,
                        line_length = 1,
                        priority = "high",
                        scale = 0.5,
                        shift = {
                            2.375,
                            -0.921875
                        },
                        width = 74,
                        repeat_count = 6,
                    }
                }
            }
        },
        working_visualisations = {
            {
                north_animation = {
                    layers = {
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north-glow.png",
                            frame_count = 6,
                            height = 336,
                            line_length = 3,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                0,
                                -0.125
                            },
                            width = 202,
                        },
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north-input-1-glow.png",
                            height = 176,
                            line_length = 1,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                -0.765625,
                                1.296875
                            },
                            width = 104,
                            repeat_count = 6,
                        },
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/north/fusion-generator-north-input-2-glow.png",
                            height = 166,
                            line_length = 1,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                0.796875,
                                1.34375
                            },
                            width = 102,
                            repeat_count = 6,
                        }
                    }
                },
                east_animation = {
                    layers = {
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east-input-1-glow.png",
                            height = 80,
                            line_length = 1,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                -1.640625,
                                -0.96875
                            },
                            width = 118,
                            repeat_count = 6,
                        },
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east-input-2-glow.png",
                            height = 146,
                            line_length = 1,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                -1.609375,
                                0.375
                            },
                            width = 122,
                            repeat_count = 6,
                        },
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/east/fusion-generator-east-glow.png",
                            frame_count = 6,
                            height = 226,
                            line_length = 3,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                0.015625,
                                -0.0625
                            },
                            width = 322,
                        }
                    }
                },
                south_animation = {
                    layers = {
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south-glow.png",
                            frame_count = 6,
                            height = 326,
                            line_length = 3,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                0.015625,
                                0.125
                            },
                            width = 204,
                        },
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south-input-1-glow.png",
                            height = 146,
                            line_length = 1,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                0.796875,
                                -1.703125
                            },
                            width = 104,
                            repeat_count = 6,
                        },
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/south/fusion-generator-south-input-2-glow.png",
                            height = 146,
                            line_length = 1,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                -0.734375,
                                -1.71875
                            },
                            width = 106,
                            repeat_count = 6,
                        },
                    }
                },
                west_animation = {
                    layers = {
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west-input-1-glow.png",
                            height = 140,
                            line_length = 1,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                1.625,
                                0.4375
                            },
                            width = 120,
                            repeat_count = 6,
                        },
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west-input-2-glow.png",
                            height = 74,
                            line_length = 1,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                1.96875,
                                -1.046875
                            },
                            width = 76,
                            repeat_count = 6,
                        },
                        {
                            blend_mode = "additive",
                            draw_as_glow = true,
                            filename = "__space-age__/graphics/entity/fusion-generator/west/fusion-generator-west-glow.png",
                            frame_count = 6,
                            height = 226,
                            line_length = 3,
                            priority = "high",
                            scale = 0.5,
                            shift = {
                                0,
                                -0.09375
                            },
                            width = 322,
                        }
                    }
                }
            },
        }
    }

    fusion_plant.fluid_boxes = {
        {
            production_type = "input",
            --pipe_covers = pipecoverspictures(),
            volume = 10,
            filter = "fusion-plasma",
            pipe_connections = {
                { flow_direction = "input", direction = defines.direction.south, position = { -1, 2 }, connection_category = { "fusion-plasma" } },
                { flow_direction = "input", direction = defines.direction.south, position = { 1, 2 }, connection_category = { "fusion-plasma" } },
                { flow_direction = "output", direction = defines.direction.north, position = { 0, -2 }, connection_category = { "fusion-plasma" } },
                { flow_direction = "output", direction = defines.direction.west, position = { -1, 0 }, connection_category = { "fusion-plasma" } },
                { flow_direction = "output", direction = defines.direction.east, position = { 1, 0 }, connection_category = { "fusion-plasma" } },
                { flow_direction = "output", direction = defines.direction.west, position = { -1, -1 }, connection_category = { "fusion-plasma" } },
                { flow_direction = "output", direction = defines.direction.east, position = { 1, -1 }, connection_category = { "fusion-plasma" } },
            },
        },
        {
            production_type = "output",
            pipe_covers = pipecoverspictures(),
            volume = 100,
            filter = "fluoroketone-hot",
            pipe_connections = {
                { flow_direction = "output", direction = defines.direction.north, position = { -1, -2 } },
                { flow_direction = "output", direction = defines.direction.north, position = { 1, -2 } },
            }
        }
    }
    data.extend({
        {
            type = "recipe-category",
            name = "fusion-assembly"
        },
        fusion_plant
    })
end

local function create_item()
    local fusion_plant = util.table.deepcopy(data.raw['item']['fusion-generator'])
    fusion_plant.name = "fusion-assembling-machine"
    fusion_plant.place_result = "fusion-assembling-machine"

    data:extend({ fusion_plant })
end

local function create_recipe()
    local fusion_plant = util.table.deepcopy(data.raw['recipe']['fusion-generator'])
    fusion_plant.name = "fusion-assembling-machine"
    fusion_plant.subgroup = "production-machine"
    fusion_plant.results = { { type = "item", name = "fusion-assembling-machine", amount = 1 } },

    data:extend({ fusion_plant })

    local tech = data.raw["technology"]["fusion-reactor"]
    table.insert(tech.effects, {
        type = "unlock-recipe",
        recipe = "fusion-assembling-machine"
    })
end

function FusionEconomyHelper.init()
    if not data.raw['assembling-machine']['fusion-assembling-machine'] then
        create_entity()
        create_item()
        create_recipe()
    end
end

return FusionEconomyHelper