---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/1/2024 11:15 AM
---

require("util")
local MapGenFunctions = {}

--- enemy with non enemy_base name
local exclude_autoplace = {
    
}

MapGenFunctions.remove_enemy_autoplace_controls = function(autoplace_controls)
    for key, _ in pairs(autoplace_controls) do
        if string.find(key,"enemy_base", nil, true) or 
           string.find(key,"enemy-base", nil, true) or
           exclude_autoplace[key] 
        then
            autoplace_controls[key] = nil
        end
    end
end


return MapGenFunctions