---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 4/20/2025 1:29 PM
---
local hit_effects = require ("__base__.prototypes.entity.hit-effects")

local PsiScanner = {}

---
--- PSI radar to scan boss on their home planet
---
function PsiScanner.make_entity(prefix, icons, surface_conditions)
    local psi_scanner_entity = 
    {
        type = "radar",
        name = prefix.."--psi-radar",
        icons = icons,
        flags = {"placeable-player", "player-creation", "not-repairable"},
        minable = nil,
        create_ghost_on_death = false,
        alert_when_damaged = true,
        allow_copy_paste = false,
        max_health = 1000000,
        corpse = "radar-remnants",
        dying_explosion = "radar-explosion",
        resistances =
        {
            { type = "acid", percent = 80 },
            { type = "poison", percent = 80 },
            { type = "physical", percent = 80 },
            { type = "fire", percent = 80 },
            { type = "explosion", percent = 80 },
            { type = "laser", percent = 80 },
            { type = "electric", percent = 80 },
            { type = "cold", percent = 80 }
        },
        collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
        selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
        damaged_trigger_effect = hit_effects.entity(),
        energy_per_sector = "5MJ",
        max_distance_of_sector_revealed = 15,
        max_distance_of_nearby_sector_revealed = 5,
        energy_per_nearby_scan = "500kJ",
        energy_source =
        {
            type = "electric",
            usage_priority = "secondary-input"
        },
        energy_usage = "1MW",
        integration_patch =
        {
            filename = "__base__/graphics/entity/radar/radar-integration.png",
            priority = "low",
            width = 238,
            height = 216,
            shift = util.by_pixel(1.5, 4.0),
            scale = 0.5
        },
        pictures =
        {
            layers =
            {
                {
                    filename = "__base__/graphics/entity/radar/radar.png",
                    priority = "low",
                    width = 196,
                    height = 254,
                    apply_projection = false,
                    direction_count = 64,
                    line_length = 8,
                    shift = util.by_pixel(1.0, -16.0),
                    scale = 0.5
                },
                {
                    filename = "__base__/graphics/entity/radar/radar-shadow.png",
                    priority = "low",
                    width = 336,
                    height = 170,
                    apply_projection = false,
                    direction_count = 64,
                    line_length = 8,
                    shift = util.by_pixel(39.0, 6.0),
                    draw_as_shadow = true,
                    scale = 0.5
                }
            }
        },
        impact_category = "metal",
        working_sound =
        {
            sound = {filename = "__base__/sound/radar.ogg", volume = 0.8, modifiers = volume_multiplier("main-menu", 2.0)},
            max_sounds_per_prototype = 3,
            use_doppler_shift = false
        },
        radius_minimap_visualisation_color = {0.059, 0.092, 0.235, 0.275},
        rotation_speed = 0.02,
        water_reflection =
        {
            pictures =
            {
                filename = "__base__/graphics/entity/radar/radar-reflection.png",
                priority = "extra-high",
                width = 28,
                height = 32,
                shift = util.by_pixel(5, 35),
                variation_count = 1,
                scale = 5
            },
            rotate = false,
            orientation_to_variation = false
        },
        is_military_target = true,
        circuit_connector = circuit_connector_definitions["radar"],
        circuit_wire_max_distance = default_circuit_wire_max_distance,
        surface_conditions = surface_conditions
    }

    data:extend({ 
        psi_scanner_entity,
    })
end

function PsiScanner.make_item(prefix, icons)

    local psi_scanner_item =  {
        type = "item",
        name = prefix.."--psi-radar",
        icons = icons,
        subgroup = "defensive-structure",
        order = "m["..prefix.."--psi-radar]",
        place_result = prefix.."--psi-radar",
        stack_size = 1,
    }
    
    data:extend({
        psi_scanner_item,
    })
end

function PsiScanner.make_recipe(prefix, ingredients)
    
    local psi_scanner_recipe = {
        type = "recipe",
        name = prefix.."--psi-radar",
        energy_required = 10,
        enabled = false,
        category = "crafting",
        ingredients = ingredients,
        results = {
            {type="item", name=prefix.."--psi-radar", amount=1},
        },
        requester_paste_multiplier = 1,
        allow_quality = false,
    }
    
    data:extend({
        psi_scanner_recipe
    })
end

return PsiScanner