---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/16/2024 6:01 PM
---

require("util")
local SoundUtil = {}

function SoundUtil.get_aggregation(instances)
    return {
        max_count = instances,
        count_already_playing = true,
        priority = "closest",
        remove = true,
    }
end

return SoundUtil