---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/16/2024 6:01 PM
---

require("util")
local SoundUtil = {}

function SoundUtil.get_aggregation(instances)
    return {
        max_count = instances,
        count_already_playing = true,
        priority = "closest",
        remove = true,
    }
end


function SoundUtil.dupe_planet_music(planet_name, new_planet_name)
    local sound_list = {}
    local index = 1
    for _, sound in pairs(data.raw['ambient-sound']) do
        if sound['planet'] == planet_name then
            local new_sound = util.table.deepcopy(sound)
            new_sound.name = new_planet_name .. '-' .. index
            new_sound.planet = new_planet_name
            table.insert(sound_list, new_sound)
            index = index + 1
        end
    end
    return sound_list
end

return SoundUtil